[book]
authors = ["Gavin Niederman", "Lewis McClelland", "Tropical"]
language = "en"
src = "src"
title = "vexide internal docs"

[output.html]
git-repository-url = "https://github.com/vexide/internal-documentation"
fold = { enable = true, level = 2 }
site-url = "internals.vexide.dev"
mathjax-support = true
